<a href="https://colab.research.google.com/github/9490549112/22A81A0574-/blob/main/DA_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#random module is sub-package of numpy

In [ ]:
A=np.random.rand(1)
print(A)

[0.68078972]


In [ ]:
A=np.random.rand(8,4)#rand-range is between 0 and 1
print(A)

[[0.43106254 0.00638945 0.58044628 0.58552127]
 [0.90660275 0.85184245 0.31753548 0.28547141]
 [0.69772706 0.02597299 0.36137501 0.16939355]
 [0.73434311 0.9178159  0.12084058 0.39124888]
 [0.90912588 0.13650759 0.96007609 0.63719241]
 [0.05690207 0.56646375 0.25132877 0.62746288]
 [0.00833504 0.08651565 0.28447627 0.77814103]
 [0.51998792 0.23918444 0.77579633 0.52310882]]


In [ ]:
A=10*np.random.rand(8,4)#rand-range is between 0 and 1
print(A)

[[5.91957948 6.47787859 7.31941765 8.35847938]
 [1.07173519 1.71948112 3.07556918 0.20857338]
 [9.28034742 1.91125212 9.75745976 8.46045413]
 [7.2270749  6.20980195 2.12127748 3.08879924]
 [6.36636356 2.30588137 8.04189747 6.96942264]
 [4.23358207 2.2098229  4.18094989 8.17395713]
 [5.96972341 7.02274633 0.84459493 9.70784667]
 [7.91538358 1.85121157 7.96458089 0.49723393]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))#rand-range is between 0 and 1
print(A)

[[8. 9. 3. 5.]
 [4. 6. 2. 6.]
 [9. 6. 6. 6.]
 [7. 2. 7. 1.]
 [7. 5. 3. 7.]
 [6. 4. 8. 0.]
 [8. 2. 3. 9.]
 [4. 1. 9. 3.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4)#Vertical split

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(3,4))#split it after 3rd row and 4th row

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)#horizontal split

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(2,5))#split it after 2nd column and 5th column

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4,  5],
        [11, 12, 13],
        [19, 20, 21],
        [27, 28, 29]]),
 array([[ 6,  7,  8],
        [14, 15, 16],
        [22, 23, 24],
        [30, 31, 32]])]

Trigonometry

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A)#Convert radius to degrees
print(B)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(B)#Convert degrees to radius

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)#radians

0.8414709848078965

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.tan(1)

1.5574077246549023

In [ ]:
st=np.array([23,45,67,89,21,34])

In [ ]:
np.mean(st)#mean

46.5

In [ ]:
np.median(st)#median

39.5

In [ ]:
np.std(st)#Standard deviation

24.452334585202017

In [ ]:
np.var(st)#varience

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)#inverse of a matrix C

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)

[[9.02323208 1.55916431 5.7869243  1.15896762]
 [8.58542762 8.88435373 6.34700885 6.29412099]
 [7.625101   1.58871234 4.3454554  1.90002916]
 [9.89493403 6.19176114 8.81049122 4.81126603]
 [3.82034782 5.52195523 1.5375197  8.44034302]
 [7.30595323 8.30212808 5.09509205 7.07072758]]


In [ ]:
print(np.argmax(C))#index of maximum number

12


In [ ]:
print(np.argmax(C,axis=0))#indexes of maximum numbers in each column

[3 1 3 4]


In [ ]:
print(np.argmax(C,axis=1))#indexes of maximum numbers in each row

[0 1 0 0 3 1]


In [ ]:
print(np.argmin(C))#index of minimum number

3


In [ ]:
print(np.argmin(C,axis=0))#indexes of minimum numbers in each column

[4 0 4 0]


In [ ]:
print(np.argmin(C,axis=1))#indexes of minimum numbers in each row

[3 3 1 3 2 2]


Searching

In [ ]:
a=np.array([34,56,7,17,88,91])
print(np.where(a%2==0))#prints even numbers in the array

(array([0, 1, 4]),)


In [ ]:
b=np.array([24,16,7,17,54,60])
print(np.where(b%6==0))#items divisible by 6

(array([0, 4, 5]),)


In [ ]:
c=np.array([6,7,8,9,10])#used only for sorted list
x=np.searchsorted(c,10)#prints index of 10 in the array
print(x)

4


In [ ]:
#sorting array
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

arr=np.array([True,False,True])
print(np.sort(arr))

['apple' 'banana' 'cherry']
[False  True  True]


In [ ]:
#Sorting happens within row
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
arr=np.array([40,43,50,44,67,78])
filt=np.where(arr%2==0)
print(filt)

(array([0, 2, 3, 5]),)


In [ ]:
arr[filt]

array([40, 50, 44, 78])

Iterating through 2 arrays (zip)

In [ ]:
names=np.array(["prasanna","pilli pilla","suji","sumakka"])
initials=np.array(["Ch","Y","E","M"])
for i,j in zip(initials,names):
  print(i,".",j)

Ch . prasanna
Y . pilli pilla
E . suji
M . sumakka


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


Logarithms

In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log(a1))#natural log e

[1 2 3 4 5 6 7 8 9]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
a1=np.arange(1,10)
print(a1)
print(np.log2(a1))#log base2

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [ ]:
a=1.2
print(np.log10(a))#log base 10

0.07918124604762482


Other mathematical fuctions

In [ ]:
a2=np.array([5,6,7,10])
x=np.cumsum(a2)#cumulative sum
print(x)

[ 5 11 18 28]


In [ ]:
a2=np.array([5,6,7,10])
x=np.cumprod(a2)#cumulative product
print(x)

[   5   30  210 2100]


In [ ]:
a1=np.array([10,15,25,15])#e2-e1
newarr=np.diff(a1)#difference
print(newarr)

[  5  10 -10]


In [ ]:
num1=455
num2=665
x=np.lcm(num1,num2)#lcm
print(x)

8645


In [ ]:
num1=455
num2=665
x=np.gcd(num1,num2)#gcd
print(x)

35


In [ ]:
a=np.array([12,15,60])
gc=np.gcd.reduce(a)#takes multiple inputs gives single product
print(gc)

3


In [ ]:
a=np.array([12,15,60])
lc=np.lcm.reduce(a)#takes multiple inputs gives single product
print(lc)

60
